//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int IDFuncionario { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CodFuncionario { get; set; }
        public string Cargo { get; set; }
        public string Departamento { get; set; }
    }
}
